kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "prefect-agent.name" . }}
  labels:
    {{- include "prefect-agent.labels" . | nindent 4 }}
rules:
  - verbs:
      - '*'
    apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
