kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "prefect-agent.name" . }}
  labels:
    {{- include "prefect-agent.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.agent.serviceAccountName }}
    namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "prefect-agent.name" . }}
