image:
  repository: prefecthq/prefect
  tag: 1.2.0-python3.7

namespace: default

agent:
  serviceAccountName: 'prefect-agent'

  token: ''

  labels: ''

job:
  imagePullSecret: ''

  resources:
    requests:
      cpu: ''
      memory: ''
    limits:
      cpu: '2'
      memory: '2Gi'
