{{ if .Values.configs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "simple-app.fullname" . }}
  labels:
    {{- include "simple-app.labels" . | nindent 4 }}
data:
  {{- range .Values.configs }}
  {{ .name }}: |
    {{- .value | nindent 4 }}
  {{- end }}
{{ end }}
