{{- if .Values.gateway.enabled -}}
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: {{ include "simple-app.fullname" . }}
  labels:
    {{- include "simple-app.labels" . | nindent 4 }}
spec:
  default:
    timeoutSec: {{ .Values.timeoutSec}}
    {{ if .Values.gke.iap.enabled }}
    iap:
      enabled: true
      oauth2ClientSecret:
        name: {{ .Values.gke.iap.oauth2ClientSecret}}
      clientID: {{ .Values.gke.iap.clientID}}
    {{ end }}
  targetRef:
    group: ""
    kind: Service
    name: {{ include "simple-app.fullname" . }}
{{- end -}}
