{{- if .Values.gateway.enabled -}}
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: {{ include "simple-app.fullname" . }}
  labels:
    {{- include "simple-app.labels" . | nindent 4 }}
spec:
  parentRefs:
  - kind: Gateway
    name: {{ .Values.gateway.name }}
  hostnames:
  - "{{ .Values.domain }}"
  rules:
  - backendRefs:
    - name: {{ include "simple-app.fullname" . }}
      port: {{ .Values.servicePort }}
{{- end -}}
