{{- if .Values.ingress.enabled -}}
{{- $fullName := include "simple-app.fullname" . -}}
{{- $svcPort := .Values.servicePort -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "simple-app.labels" . | nindent 4 }}
  annotations:
  {{- if .Values.ingress.nginx }}
    kubernetes.io/ingress.class: nginx
  {{- end }}
  {{- if .Values.gke.managedCertificate.enabled }}
    networking.gke.io/managed-certificates: {{ include "simple-app.fullname" . }}
  {{- end }}
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: {{ if .Values.ingress.nginx }}/{{ else }}/*{{ end }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port: 
                  number: {{ $svcPort }}
  {{- end }}
