{{- if .Values.gke.managedCertificate.enabled }}
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: {{ include "simple-app.fullname" . }}
spec:
  domains:
    - {{ .Values.domain }}
{{- end }}