{{ if .Values.monitoringCoreos.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "simple-app.labels" . | nindent 4 }}
  name: {{ include "simple-app.fullname" . }}
spec:
  endpoints:
    - path: {{ .Values.monitoringCoreos.path }}
      port: {{ .Values.monitoringCoreos.port }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "simple-app.selectorLabels" . | nindent 6 }}
{{ end }}