apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-app.fullname" . }}
  labels:
    {{- include "simple-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.servicePort | default .Values.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- range .Values.extraPorts}}
    - port: {{ .servicePort | default .port }}
      targetPort: {{ .name }}
      protocol: {{ .protocol | default "TCP" }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "simple-app.selectorLabels" . | nindent 4 }}
