name: Run tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.0

      - name: Install helm-unittest
        run: |
          helm plugin install https://github.com/helm-unittest/helm-unittest.git

      - name: Run tests
        run: |
          helm unittest charts/* -o test-result.xml -t junit

      - name: Test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: helm unittest
          path: test-result.xml
          reporter: java-junit
